COLLECTOR_VERSION_MAJOR = 1
COLLECTOR_VERSION_MINOR = 5
COLLECTOR_VERSION_PATCH = 2
COLLECTOR_VERSION = $(COLLECTOR_VERSION_MAJOR).$(COLLECTOR_VERSION_MINOR).$(COLLECTOR_VERSION_PATCH)
COLLECTOR_VERSION_SUFFIX = -SNAPSHOT
COLLECTOR_REVISION = 1
