COLLECTOR_VERSION_MAJOR = 1
COLLECTOR_VERSION_MINOR = 2
COLLECTOR_VERSION_PATCH = 0
COLLECTOR_VERSION = $(COLLECTOR_VERSION_MAJOR).$(COLLECTOR_VERSION_MINOR).$(COLLECTOR_VERSION_PATCH)
COLLECTOR_VERSION_SUFFIX =
COLLECTOR_REVISION = 1
