dist:
  name: graylog-collector
  description: Graylog Collector
  version: 2.0.0-SNAPSHOT
  output_path: ./builder
  cgo_enabled: false

extensions:
  - gomod: github.com/Graylog2/collector-sidecar/extension/sidecar v1.5.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension v0.146.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.146.1
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.146.1
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.146.1
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.146.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.146.1
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.146.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/macosunifiedloggingreceiver v0.146.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/windowseventlogreceiver v0.146.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.52.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.52.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.52.0

replaces:
  - github.com/Graylog2/collector-sidecar/extension/sidecar => ../extension/sidecar
  - github.com/Graylog2/collector-sidecar/superv => ../superv
