// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module go.opentelemetry.io/collector/cmd/builder

go 1.26.0

require (
	github.com/Graylog2/collector-sidecar/extension/sidecar v1.5.0
	github.com/Graylog2/collector-sidecar/receiver/windowseventlogreceiver v0.0.0
	github.com/Graylog2/collector-sidecar/superv v0.0.0-00010101000000-000000000000
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.150.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension v0.150.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.150.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.150.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.150.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/journaldreceiver v0.150.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/macosunifiedloggingreceiver v0.150.0
	github.com/spf13/cobra v1.10.2
	go.opentelemetry.io/collector/component v1.56.0
	go.opentelemetry.io/collector/confmap v1.56.0
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.56.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.56.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.56.0
	go.opentelemetry.io/collector/connector v0.150.0
	go.opentelemetry.io/collector/exporter v1.56.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.150.0
	go.opentelemetry.io/collector/exporter/nopexporter v0.150.0
	go.opentelemetry.io/collector/exporter/otlpexporter v0.150.0
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.150.0
	go.opentelemetry.io/collector/extension v1.56.0
	go.opentelemetry.io/collector/otelcol v0.150.0
	go.opentelemetry.io/collector/processor v1.56.0
	go.opentelemetry.io/collector/receiver v1.56.0
	go.opentelemetry.io/collector/receiver/nopreceiver v0.150.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.150.0
	go.opentelemetry.io/collector/service v0.150.0
	go.uber.org/zap v1.27.1
	golang.org/x/sys v0.43.0
)

require (
	github.com/DeRuina/timberjack v1.4.0 // indirect
	github.com/beorn7/perks v1.0.1 // indirect
	github.com/bmatcuk/doublestar/v4 v4.10.0 // indirect
	github.com/cenkalti/backoff/v4 v4.3.0 // indirect
	github.com/cenkalti/backoff/v5 v5.0.3 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
	github.com/docker/go-units v0.5.0 // indirect
	github.com/ebitengine/purego v0.10.0 // indirect
	github.com/elastic/go-ucfg v0.9.1 // indirect
	github.com/elastic/gosigar v0.14.4 // indirect
	github.com/elastic/lunes v0.2.0 // indirect
	github.com/expr-lang/expr v1.17.8 // indirect
	github.com/fatih/structs v1.1.0 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568 // indirect
	github.com/foxboron/go-tpm-keyfiles v0.0.0-20251226215517-609e4778396f // indirect
	github.com/fsnotify/fsnotify v1.9.0 // indirect
	github.com/go-logr/logr v1.4.3 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/go-ole/go-ole v1.2.6 // indirect
	github.com/go-viper/mapstructure/v2 v2.5.0 // indirect
	github.com/gobwas/glob v0.2.3 // indirect
	github.com/goccy/go-json v0.10.6 // indirect
	github.com/goccy/go-yaml v1.19.2 // indirect
	github.com/golang-jwt/jwt/v5 v5.3.1 // indirect
	github.com/golang/snappy v1.0.0 // indirect
	github.com/google/go-tpm v0.9.8 // indirect
	github.com/google/renameio/v2 v2.0.2 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/gorilla/websocket v1.5.3 // indirect
	github.com/grpc-ecosystem/grpc-gateway/v2 v2.28.0 // indirect
	github.com/hashicorp/go-version v1.9.0 // indirect
	github.com/hashicorp/golang-lru/v2 v2.0.7 // indirect
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/jonboulle/clockwork v0.5.0 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/kardianos/service v1.2.4 // indirect
	github.com/klauspost/compress v1.18.5 // indirect
	github.com/knadh/koanf/maps v0.1.2 // indirect
	github.com/knadh/koanf/parsers/yaml v1.1.0 // indirect
	github.com/knadh/koanf/providers/confmap v1.0.0 // indirect
	github.com/knadh/koanf/providers/env/v2 v2.0.0 // indirect
	github.com/knadh/koanf/providers/file v1.2.1 // indirect
	github.com/knadh/koanf/providers/rawbytes v1.0.0 // indirect
	github.com/knadh/koanf/providers/structs v1.0.0 // indirect
	github.com/knadh/koanf/v2 v2.3.4 // indirect
	github.com/leodido/go-syslog/v4 v4.4.0 // indirect
	github.com/leodido/ragel-machinery v0.0.0-20190525184631-5f46317e436b // indirect
	github.com/lufia/plan9stats v0.0.0-20251013123823-9fd1530e3ec3 // indirect
	github.com/magefile/mage v1.17.1 // indirect
	github.com/michel-laterman/proxy-connect-dialer-go v0.1.0 // indirect
	github.com/mitchellh/copystructure v1.2.0 // indirect
	github.com/mitchellh/reflectwalk v1.0.2 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.3-0.20250322232337-35a7c28c31ee // indirect
	github.com/mostynb/go-grpc-compression v1.2.3 // indirect
	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
	github.com/natefinch/lumberjack v2.0.0+incompatible // indirect
	github.com/oklog/ulid/v2 v2.1.1 // indirect
	github.com/open-telemetry/opamp-go v0.23.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampcustommessages v0.150.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/common v0.150.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal v0.150.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/healthcheck v0.150.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza v0.150.0 // indirect
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/status v0.150.0 // indirect
	github.com/pborman/uuid v1.2.1 // indirect
	github.com/pierrec/lz4/v4 v4.1.26 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2 // indirect
	github.com/power-devops/perfstat v0.0.0-20240221224432-82ca36839d55 // indirect
	github.com/prometheus/client_golang v1.23.2 // indirect
	github.com/prometheus/client_model v0.6.2 // indirect
	github.com/prometheus/common v0.67.5 // indirect
	github.com/prometheus/otlptranslator v1.0.0 // indirect
	github.com/prometheus/procfs v0.20.1 // indirect
	github.com/rifflock/lfshook v0.0.0-20180920164130-b9218ef580f5 // indirect
	github.com/rs/cors v1.11.1 // indirect
	github.com/shirou/gopsutil/v4 v4.26.3 // indirect
	github.com/sirupsen/logrus v1.9.4 // indirect
	github.com/spf13/pflag v1.0.10 // indirect
	github.com/stretchr/testify v1.11.1 // indirect
	github.com/tklauser/go-sysconf v0.3.16 // indirect
	github.com/tklauser/numcpus v0.11.0 // indirect
	github.com/valyala/fastjson v1.6.10 // indirect
	github.com/yusufpapurcu/wmi v1.2.4 // indirect
	go.etcd.io/bbolt v1.4.3 // indirect
	go.opentelemetry.io/auto/sdk v1.2.1 // indirect
	go.opentelemetry.io/collector v0.150.0 // indirect
	go.opentelemetry.io/collector/client v1.56.0 // indirect
	go.opentelemetry.io/collector/component/componentstatus v0.150.0 // indirect
	go.opentelemetry.io/collector/component/componenttest v0.150.0 // indirect
	go.opentelemetry.io/collector/config/configauth v1.56.0 // indirect
	go.opentelemetry.io/collector/config/configcompression v1.56.0 // indirect
	go.opentelemetry.io/collector/config/configgrpc v0.150.0 // indirect
	go.opentelemetry.io/collector/config/confighttp v0.150.0 // indirect
	go.opentelemetry.io/collector/config/configmiddleware v1.56.0 // indirect
	go.opentelemetry.io/collector/config/confignet v1.56.0 // indirect
	go.opentelemetry.io/collector/config/configopaque v1.56.0 // indirect
	go.opentelemetry.io/collector/config/configoptional v1.56.0 // indirect
	go.opentelemetry.io/collector/config/configretry v1.56.0 // indirect
	go.opentelemetry.io/collector/config/configtelemetry v0.150.0 // indirect
	go.opentelemetry.io/collector/config/configtls v1.56.0 // indirect
	go.opentelemetry.io/collector/confmap/xconfmap v0.150.0 // indirect
	go.opentelemetry.io/collector/connector/connectortest v0.150.0 // indirect
	go.opentelemetry.io/collector/connector/xconnector v0.150.0 // indirect
	go.opentelemetry.io/collector/consumer v1.56.0 // indirect
	go.opentelemetry.io/collector/consumer/consumererror v0.150.0 // indirect
	go.opentelemetry.io/collector/consumer/consumererror/xconsumererror v0.150.0 // indirect
	go.opentelemetry.io/collector/consumer/consumertest v0.150.0 // indirect
	go.opentelemetry.io/collector/consumer/xconsumer v0.150.0 // indirect
	go.opentelemetry.io/collector/exporter/exporterhelper v0.150.0 // indirect
	go.opentelemetry.io/collector/exporter/exporterhelper/xexporterhelper v0.150.0 // indirect
	go.opentelemetry.io/collector/exporter/exportertest v0.150.0 // indirect
	go.opentelemetry.io/collector/exporter/xexporter v0.150.0 // indirect
	go.opentelemetry.io/collector/extension/extensionauth v1.56.0 // indirect
	go.opentelemetry.io/collector/extension/extensioncapabilities v0.150.0 // indirect
	go.opentelemetry.io/collector/extension/extensionmiddleware v0.150.0 // indirect
	go.opentelemetry.io/collector/extension/extensiontest v0.150.0 // indirect
	go.opentelemetry.io/collector/extension/xextension v0.150.0 // indirect
	go.opentelemetry.io/collector/featuregate v1.56.0 // indirect
	go.opentelemetry.io/collector/internal/componentalias v0.150.0 // indirect
	go.opentelemetry.io/collector/internal/fanoutconsumer v0.150.0 // indirect
	go.opentelemetry.io/collector/internal/sharedcomponent v0.150.0 // indirect
	go.opentelemetry.io/collector/internal/telemetry v0.150.0 // indirect
	go.opentelemetry.io/collector/pdata v1.56.0 // indirect
	go.opentelemetry.io/collector/pdata/pprofile v0.150.0 // indirect
	go.opentelemetry.io/collector/pdata/testdata v0.150.0 // indirect
	go.opentelemetry.io/collector/pdata/xpdata v0.150.0 // indirect
	go.opentelemetry.io/collector/pipeline v1.56.0 // indirect
	go.opentelemetry.io/collector/pipeline/xpipeline v0.150.0 // indirect
	go.opentelemetry.io/collector/processor/processorhelper v0.150.0 // indirect
	go.opentelemetry.io/collector/processor/processorhelper/xprocessorhelper v0.150.0 // indirect
	go.opentelemetry.io/collector/processor/processortest v0.150.0 // indirect
	go.opentelemetry.io/collector/processor/xprocessor v0.150.0 // indirect
	go.opentelemetry.io/collector/receiver/receiverhelper v0.150.0 // indirect
	go.opentelemetry.io/collector/receiver/receivertest v0.150.0 // indirect
	go.opentelemetry.io/collector/receiver/xreceiver v0.150.0 // indirect
	go.opentelemetry.io/collector/service/hostcapabilities v0.150.0 // indirect
	go.opentelemetry.io/contrib/bridges/otelzap v0.18.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.68.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.68.0 // indirect
	go.opentelemetry.io/contrib/otelconf v0.23.0 // indirect
	go.opentelemetry.io/contrib/propagators/b3 v1.43.0 // indirect
	go.opentelemetry.io/otel v1.43.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc v0.19.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp v0.19.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.43.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.43.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.43.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.43.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.43.0 // indirect
	go.opentelemetry.io/otel/exporters/prometheus v0.65.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdoutlog v0.19.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v1.43.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.43.0 // indirect
	go.opentelemetry.io/otel/log v0.19.0 // indirect
	go.opentelemetry.io/otel/metric v1.43.0 // indirect
	go.opentelemetry.io/otel/sdk v1.43.0 // indirect
	go.opentelemetry.io/otel/sdk/log v0.19.0 // indirect
	go.opentelemetry.io/otel/sdk/metric v1.43.0 // indirect
	go.opentelemetry.io/otel/trace v1.43.0 // indirect
	go.opentelemetry.io/proto/otlp v1.10.0 // indirect
	go.uber.org/multierr v1.11.0 // indirect
	go.yaml.in/yaml/v2 v2.4.4 // indirect
	go.yaml.in/yaml/v3 v3.0.4 // indirect
	golang.org/x/crypto v0.49.0 // indirect
	golang.org/x/exp v0.0.0-20260312153236-7ab1446f8b90 // indirect
	golang.org/x/net v0.52.0 // indirect
	golang.org/x/text v0.36.0 // indirect
	gonum.org/v1/gonum v0.17.0 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20260406210006-6f92a3bedf2d // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20260414002931-afd174a4e478 // indirect
	google.golang.org/grpc v1.80.0 // indirect
	google.golang.org/protobuf v1.36.11 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)

replace github.com/Graylog2/collector-sidecar/extension/sidecar => ../extension/sidecar

replace github.com/Graylog2/collector-sidecar/receiver/windowseventlogreceiver => ../receiver/windowseventlogreceiver

replace github.com/Graylog2/collector-sidecar/superv => ../superv
